/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TicTacToeRouteImport } from "./routes/tic-tac-toe";
import { Route as TradingviewRouteImport } from "./routes/tradingview";

const TradingviewRoute = TradingviewRouteImport.update({
  id: "/tradingview",
  path: "/tradingview",
  getParentRoute: () => rootRouteImport,
} as any);
const TicTacToeRoute = TicTacToeRouteImport.update({
  id: "/tic-tac-toe",
  path: "/tic-tac-toe",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/tic-tac-toe": typeof TicTacToeRoute;
  "/tradingview": typeof TradingviewRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/tic-tac-toe": typeof TicTacToeRoute;
  "/tradingview": typeof TradingviewRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/tic-tac-toe": typeof TicTacToeRoute;
  "/tradingview": typeof TradingviewRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/tic-tac-toe" | "/tradingview";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/tic-tac-toe" | "/tradingview";
  id: "__root__" | "/" | "/tic-tac-toe" | "/tradingview";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  TicTacToeRoute: typeof TicTacToeRoute;
  TradingviewRoute: typeof TradingviewRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tradingview": {
      id: "/tradingview";
      path: "/tradingview";
      fullPath: "/tradingview";
      preLoaderRoute: typeof TradingviewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tic-tac-toe": {
      id: "/tic-tac-toe";
      path: "/tic-tac-toe";
      fullPath: "/tic-tac-toe";
      preLoaderRoute: typeof TicTacToeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TicTacToeRoute: TicTacToeRoute,
  TradingviewRoute: TradingviewRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
